### ISSUE TITLE
Printing doesn't work

### ISSUE THREAD

**Issue by thjderjktyrjkt** [flathub/org.kde.kleopatra#14]
![image](https://user-images.githubusercontent.com/40300931/199726786-3037f09a-15cf-44c1-8cfa-098657c39492.png)

I guess you need to bundle PaperKey.

https://www.jabberwocky.com/software/paperkey/

**Comment by travier** [comment]
@thjderjktyrjkt

**Comment by thjderjktyrjkt** [comment]
@travier Yes. Thank you and @Mailaender for the fix!
